[package]
name = "yarra-game-content"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
blake3.workspace = true
game-types.workspace = true
gameplay.workspace = true
localization.workspace = true
ron.workspace = true
rusqlite.workspace = true
save.workspace = true
scripting.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
unic-langid.workspace = true

[dev-dependencies]
gameplay = { workspace = true, features = ["fixtures"] }
