[package]
name = "yarra-app-editor"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
blake3.workspace = true
environment.workspace = true
environment-compile.workspace = true
bevy.workspace = true
bevy_egui.workspace = true
crossbeam-channel.workspace = true
image = { version = "0.25", default-features = false, features = ["png", "jpeg"] }
engine.workspace = true
ron.workspace = true
serde.workspace = true
terrain-render.workspace = true
vegetation.workspace = true
vegetation-render.workspace = true
uuid.workspace = true
world.workspace = true
world-db.workspace = true
world-cook.workspace = true
