[package]
name = "yarra-engine"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
atmosphere.workspace = true
bevy.workspace = true
crossbeam-channel.workspace = true
log.workspace = true
ron.workspace = true
serde.workspace = true
terrain-render.workspace = true
vegetation.workspace = true
vegetation-render.workspace = true
world.workspace = true
world-db.workspace = true

[dev-dependencies]
world-cook.workspace = true
