gate-title = The old gate
gate-objective = Return the gate key
supplies-title = Supplies for the guard
supplies-objective = Deliver the supplies
guard-name = Gate guard
reward = You found the gate key, { $player }!
duty = The guard is still waiting.
welcome-a = Welcome, traveller.
welcome-b = Good to see you.
hostile = Make it quick.
return-key = Here is your key.
leave = Goodbye.
gate-topic = About the gate key
supply-topic = About the supplies
refuse = I will keep the key for now.
companion-aside = So this is the gate everyone talks about.
guard-reply = It was, before the key went missing.
banter-remark = Someone keeps this path clear. We are expected.
banter-reply = Then let us not keep them waiting.
training-topic = About sword lessons
training-offer = You opened my gate. I can show you how to hold a sword, for a little coin.
training-learn = Teach me. (20 gold)
training-taught = Better. Keep your guard up.
dummy-name = Training dummy
