[package]
name = "yarra-world-db"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
environment.workspace = true
environment-compile.workspace = true
blake3.workspace = true
bincode.workspace = true
rusqlite.workspace = true
serde.workspace = true
thiserror.workspace = true
vegetation.workspace = true
world.workspace = true
zstd.workspace = true
